name: Main Bot (Private Code Runner)

on:
  workflow_dispatch:

concurrency:
  group: bot-runner
  cancel-in-progress: true

jobs:
  bot:
    runs-on: ubuntu-latest
    timeout-minutes: 350

    steps:
      - name: Clone private repository
        run: |
          git clone https://x-access-token:${{ secrets.GH_TOKEN }}@github.com/${{ secrets.PRIVATE_REPO }}.git bot-code

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install system requirements
        run: |
          sudo apt-get update -qq
          sudo apt-get install -y -qq rar

      - name: Install Python requirements
        run: |
          pip install --upgrade pip
          pip install -r bot-code/requirements.txt
          pip install pytz

      - name: Run Main Bot
        env:
          BALE_BOT_TOKEN: ${{ secrets.BALE_BOT_TOKEN }}
          ADMIN_ID: ${{ secrets.ADMIN_ID }}
          API_ID: ${{ secrets.API_ID }}
          API_HASH: ${{ secrets.API_HASH }}
          SESSION_STRING: "1BJWap1wBuxapRetCSRpIvF88P_HPhqq5gegGGCK4yysZ7BwrtxialJHScN-xcI7XAMEToe5eoru0-x-dFW7-uCXzAkNtpZCOxT-JXv-wag9pJoFyT8s1iw3o2ZwJdUauXWtuT-Pd83KZou3D5KA3rCMnz1KnjYcNSO95ruUVu5oOIl3Cm33Vw8qIccl_RVlLiI3VmJaR8JlQyUQlITI2DYkYjF3plc1WgP5HYOYEmljuCFtZ8OlVlww8XBP0c3T_lcsocHkafcnUo6hNpKfiteI8rel3PsSv2ZvXEsyR9uZCAMeZCNUBYHyWxwXJJsjhQ1GthguZtBYG12rmoYVxEMnC5S-psRw="
          ARCHIVE_CHANNEL_ID: ${{ secrets.ARCHIVE_CHANNEL_ID }}
          REELS_CHANNEL_ID: ${{ secrets.REELS_CHANNEL_ID }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          GH_USERNAME: ${{ secrets.GH_USERNAME }}
          GITHUB_REPOSITORY: ${{ github.repository }}
        run: |
          cd bot-code
          timeout 320m python main.py
